# Inserts a blank line between shell prompts
add_newline = true

scan_timeout = 30

format = """
[│](bold green)\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$kubernetes\
$docker_context\
$battery\
$status\
$time\
$jobs\
$shell\
$cmd_duration\
$memory_usage\
[└─>](bold green) """
# format = "$all"
